version: "3.8"

services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - demo-vol:/app
        ports:
            - "8001:80"
        networks:
            - demo-net
        depends_on:
            - db
    db:
      image: mysql
      restart: always
      networks:
        - demo-net
      environment:
        MYSQL_ROOT_PASSWORD: example

volumes:
    demo-vol:

networks:
    demo-net:
      driver: bridge    
